# inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[username]
format = "[$user]($style)@"
style_user = "yellow"
style_root = "red"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style):"
trim_at = "-"
style = "blue"
disabled = false

[directory]
style = "purple"
truncation_length=2
truncation_symbol="../"

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'
vicmd_symbol = 'test'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"


